version: "3.7"
services:
  zookeeper:
    restart: always
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: nc -z localhost 2181 || exit - 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  kafka:
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka-volume:/bitnami"
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60

  kafka-app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=OUTSIDE://localhost:9092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy

volumes:
  kafka-volume:
  zookeeper-volume:
