version: '3'

services:
  zookeeper:
    image: arm64v8/zookeeper:latest  # Use the ARM version of Zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:29094,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka-1

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  kafka-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=OUTSIDE://kafka:9092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
